export const BLACK = '#202121';
export const PRIMARY = '#80DEFF';
export const TEXT_DARK = '#F6F6F6'; // Off white
export const BACKGROUND_LIGHT = TEXT_DARK;
export const WHITE = "#FFFFFFFF";
export const LIGHT_RED = "#EDB9A8";
export const RED = "#FF5733";
export const LIGHT_GREEN = "#BDEDA8";
export const GREEN = "#53C623";